In [15]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression as lr
from sklearn.feature_selection import f_regression as fr 
from sklearn.preprocessing import  normalize as nr
from sklearn.preprocessing import  normalize as nr2
from sklearn.preprocessing import StandardScaler  as st

In [16]:
rawdata=pd.read_csv('Multiple linear regression.csv')
data=rawdata.copy()


In [17]:
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [18]:
y=data.iloc[:,2]
x=data.iloc[:,0:2]

In [19]:
y

0     2.40
1     2.52
2     2.54
3     2.74
4     2.83
      ... 
79    3.71
80    3.71
81    3.73
82    3.76
83    3.81
Name: GPA, Length: 84, dtype: float64

In [20]:
model=lr()

In [21]:
model.fit(x,y)

LinearRegression()

In [22]:
fr=fr(x,y)

In [23]:
fr

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [24]:
fscore=fr[0]
pvalue=fr[1]

In [25]:
pvalue= pvalue.round(3)

In [26]:
predictdata=pd.DataFrame(data=[[1000,2],[1320,1],[1490,3]],columns=['SAT','Rand 1,2,3'])

In [27]:
predictdata

SAT  Rand 1,2,3
0  1000           2
1  1320           1
2  1490           3

In [28]:
model.predict(predictdata)

array([1.93303477, 2.47043797, 2.73500043])

In [29]:
normalx=nr(x)

In [30]:
normalx

array([[9.99999830e-01, 5.83430472e-04],
       [9.99998375e-01, 1.80288169e-03],
       [9.99998547e-01, 1.70454298e-03],
       [9.99998415e-01, 1.78041261e-03],
       [9.99999302e-01, 1.18133408e-03],
       [9.99999821e-01, 5.98802288e-04],
       [9.99999357e-01, 1.13378612e-03],
       [9.99999839e-01, 5.66893333e-04],
       [9.99999377e-01, 1.11607073e-03],
       [9.99998685e-01, 1.62161949e-03],
       [9.99998505e-01, 1.72910404e-03],
       [9.99999365e-01, 1.12675985e-03],
       [9.99999834e-01, 5.76368780e-04],
       [9.99998465e-01, 1.75233376e-03],
       [9.99999364e-01, 1.12803087e-03],
       [9.99999429e-01, 1.06837546e-03],
       [9.99998539e-01, 1.70939921e-03],
       [9.99999286e-01, 1.19474228e-03],
       [9.99998674e-01, 1.62866234e-03],
       [9.99998589e-01, 1.67972887e-03],
       [9.99998549e-01, 1.70357504e-03],
       [9.99998482e-01, 1.74215763e-03],
       [9.99998373e-01, 1.80396580e-03],
       [9.99999824e-01, 5.92768123e-04],
       [9.999998

In [31]:
modeln=lr()

In [32]:
modeln.fit(normalx,y)

LinearRegression()

In [33]:
predictdatan=nr(predictdata)

In [34]:
predictdatan

array([[9.99998000e-01, 1.99999600e-03],
       [9.99999713e-01, 7.57575540e-04],
       [9.99997973e-01, 2.01341874e-03]])

In [35]:
normalx

array([[9.99999830e-01, 5.83430472e-04],
       [9.99998375e-01, 1.80288169e-03],
       [9.99998547e-01, 1.70454298e-03],
       [9.99998415e-01, 1.78041261e-03],
       [9.99999302e-01, 1.18133408e-03],
       [9.99999821e-01, 5.98802288e-04],
       [9.99999357e-01, 1.13378612e-03],
       [9.99999839e-01, 5.66893333e-04],
       [9.99999377e-01, 1.11607073e-03],
       [9.99998685e-01, 1.62161949e-03],
       [9.99998505e-01, 1.72910404e-03],
       [9.99999365e-01, 1.12675985e-03],
       [9.99999834e-01, 5.76368780e-04],
       [9.99998465e-01, 1.75233376e-03],
       [9.99999364e-01, 1.12803087e-03],
       [9.99999429e-01, 1.06837546e-03],
       [9.99998539e-01, 1.70939921e-03],
       [9.99999286e-01, 1.19474228e-03],
       [9.99998674e-01, 1.62866234e-03],
       [9.99998589e-01, 1.67972887e-03],
       [9.99998549e-01, 1.70357504e-03],
       [9.99998482e-01, 1.74215763e-03],
       [9.99998373e-01, 1.80396580e-03],
       [9.99999824e-01, 5.92768123e-04],
       [9.999998

In [36]:
modeln.predict(predictdatan)

array([3.05608226, 3.39438622, 3.04660718])

In [37]:
model.predict(predictdata)

array([1.93303477, 2.47043797, 2.73500043])

In [38]:
standard=st()

In [39]:
standard.fit(x)

StandardScaler()

In [40]:
standardx=standard.transform(x)

In [41]:
models=lr()

In [42]:
models.fit(standardx,y)

LinearRegression()

In [43]:
predictdatas=standard.transform(predictdata)

In [44]:
models.predict(predictdatas)

array([1.93303477, 2.47043797, 2.73500043])

In [45]:
xnew=x.iloc[:,0]

In [46]:
xnew=xnew.values.reshape(-1,1)

In [47]:
xnew.shape

(84, 1)

In [48]:
modelnew=lr()

In [49]:
modelnew.fit(xnew,y)

LinearRegression()

In [50]:
predictdatanew=predictdata.iloc[:,0].values.reshape(-1,1)

In [51]:
modelnew.predict(predictdatanew)

array([1.93072835, 2.46054853, 2.74201549])

In [76]:
normalnew=nr2(xnew,axis=0)

In [78]:
normalnew

array([[0.10118658],
       [0.09823481],
       [0.10390221],
       [0.09947456],
       [0.09994684],
       [0.09858903],
       [0.10413835],
       [0.10413835],
       [0.10579134],
       [0.10921539],
       [0.10242632],
       [0.10478774],
       [0.10242632],
       [0.10106851],
       [0.10466967],
       [0.11051417],
       [0.10360703],
       [0.09882517],
       [0.10874311],
       [0.10543713],
       [0.10396124],
       [0.10165886],
       [0.09817578],
       [0.09959263],
       [0.11653577],
       [0.10779854],
       [0.10549616],
       [0.10750336],
       [0.1192514 ],
       [0.10590941],
       [0.10443353],
       [0.11417436],
       [0.10478774],
       [0.10951056],
       [0.11098645],
       [0.10915635],
       [0.1067359 ],
       [0.11535506],
       [0.10490581],
       [0.10809372],
       [0.11010092],
       [0.10921539],
       [0.11606349],
       [0.10047816],
       [0.11748034],
       [0.11364304],
       [0.10768047],
       [0.115

In [79]:
xnew

array([[1714],
       [1664],
       [1760],
       [1685],
       [1693],
       [1670],
       [1764],
       [1764],
       [1792],
       [1850],
       [1735],
       [1775],
       [1735],
       [1712],
       [1773],
       [1872],
       [1755],
       [1674],
       [1842],
       [1786],
       [1761],
       [1722],
       [1663],
       [1687],
       [1974],
       [1826],
       [1787],
       [1821],
       [2020],
       [1794],
       [1769],
       [1934],
       [1775],
       [1855],
       [1880],
       [1849],
       [1808],
       [1954],
       [1777],
       [1831],
       [1865],
       [1850],
       [1966],
       [1702],
       [1990],
       [1925],
       [1824],
       [1956],
       [1857],
       [1979],
       [1802],
       [1855],
       [1907],
       [1634],
       [1879],
       [1887],
       [1730],
       [1953],
       [1781],
       [1891],
       [1964],
       [1808],
       [1893],
       [2041],
       [1893],
       [1832],
       [18

In [80]:
normalnew

array([[0.10118658],
       [0.09823481],
       [0.10390221],
       [0.09947456],
       [0.09994684],
       [0.09858903],
       [0.10413835],
       [0.10413835],
       [0.10579134],
       [0.10921539],
       [0.10242632],
       [0.10478774],
       [0.10242632],
       [0.10106851],
       [0.10466967],
       [0.11051417],
       [0.10360703],
       [0.09882517],
       [0.10874311],
       [0.10543713],
       [0.10396124],
       [0.10165886],
       [0.09817578],
       [0.09959263],
       [0.11653577],
       [0.10779854],
       [0.10549616],
       [0.10750336],
       [0.1192514 ],
       [0.10590941],
       [0.10443353],
       [0.11417436],
       [0.10478774],
       [0.10951056],
       [0.11098645],
       [0.10915635],
       [0.1067359 ],
       [0.11535506],
       [0.10490581],
       [0.10809372],
       [0.11010092],
       [0.10921539],
       [0.11606349],
       [0.10047816],
       [0.11748034],
       [0.11364304],
       [0.10768047],
       [0.115

In [81]:
modelnewn=lr()

In [82]:
modelnewn.fit(normalnew,y)

LinearRegression()

In [98]:
predictdatanewn=nr2(predictdatanew,axis=0)

In [99]:
predictdatanew

array([[1000],
       [1320],
       [1490]], dtype=int64)

In [104]:
modelnewn.predict(predictdatanewn)

array([12.86476257, 16.89347369, 19.03372648])

In [85]:
standardnew=st()

In [86]:
standardnew.fit(xnew)

StandardScaler()

In [87]:
standardx=standardnew.transform(xnew)

In [88]:
standardx.shape

(84, 1)

In [89]:
predictdatanews=standardnew.transform(predictdatanew)

In [90]:
modelnews=lr()

In [91]:
modelnews.fit(standardx,y)

LinearRegression()

In [93]:
modelnews.predict(predictdatanews)

array([1.93072835, 2.46054853, 2.74201549])

In [94]:
models.predict(predictdatas)

array([1.93303477, 2.47043797, 2.73500043])

In [105]:
modelnewn.predict(predictdatanewn)

array([12.86476257, 16.89347369, 19.03372648])

In [96]:
models.predict(predictdatas)

array([1.93303477, 2.47043797, 2.73500043])