In [1]:
%pip install tensorflow-datasets

Note: you may need to restart the kernel to use updated packages.


In [ ]:
#python -m ensurepip --user --upgrade

In [3]:
%pip install ipywidgets

     ---------------------------------------- 0.0/138.3 kB ? eta -:--:--
     -- ------------------------------------- 10.2/138.3 kB ? eta -:--:--
     -- ------------------------------------- 10.2/138.3 kB ? eta -:--:--
     -- ------------------------------------- 10.2/138.3 kB ? eta -:--:--
     -- ------------------------------------- 10.2/138.3 kB ? eta -:--:--
     -- ------------------------------------- 10.2/138.3 kB ? eta -:--:--
     -- ------------------------------------- 10.2/138.3 kB ? eta -:--:--
     -- ------------------------------------- 10.2/138.3 kB ? eta -:--:--
     -------- ----------------------------- 30.7/138.3 kB 62.4 kB/s eta 0:00:02
     -------- ----------------------------- 30.7/138.3 kB 62.4 kB/s eta 0:00:02
     -------- ----------------------------- 30.7/138.3 kB 62.4 kB/s eta 0:00:02
     ----------- -------------------------- 41.0/138.3 kB 63.5 kB/s eta 0:00:02
     ---------------- --------------------- 61.4/138.3 kB 99.4 kB/s eta 0:00:01
     ----

ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'c:\\Python311\\share'
Consider using the `--user` option or check the permissions.



In [3]:
import tensorflow_datasets as dsd

In [4]:
mnistdata,mnistinfo=dsd.load(name='mnist',with_info=True,as_supervised=True)

In [5]:
mnistinfo

tfds.core.DatasetInfo(
    name='mnist',
    full_name='mnist/3.0.1',
    description="""
    The MNIST database of handwritten digits.
    """,
    homepage='http://yann.lecun.com/exdb/mnist/',
    data_path='C:\\Users\\Data Sciense\\tensorflow_datasets\\mnist\\3.0.1',
    file_format=tfrecord,
    download_size=11.06 MiB,
    dataset_size=21.00 MiB,
    features=FeaturesDict({
        'image': Image(shape=(28, 28, 1), dtype=uint8),
        'label': ClassLabel(shape=(), dtype=int64, num_classes=10),
    }),
    supervised_keys=('image', 'label'),
    disable_shuffling=False,
    splits={
        'test': <SplitInfo num_examples=10000, num_shards=1>,
        'train': <SplitInfo num_examples=60000, num_shards=1>,
    },
    citation="""@article{lecun2010mnist,
      title={MNIST handwritten digit database},
      author={LeCun, Yann and Cortes, Corinna and Burges, CJ},
      journal={ATT Labs [Online]. Available: http://yann.lecun.com/exdb/mnist},
      volume={2},
      year={2010}
    

In [6]:
mtrain,mtest=mnistdata['train'],mnistdata['test']

In [7]:
numvalidation=0.1*mnistinfo.splits['train'].num_examples

In [8]:
numvalidation

6000.0

In [9]:
import tensorflow as tf

In [10]:
numvalidation=tf.cast(numvalidation,dtype=tf.int64)

In [11]:
numtest=mnistinfo.splits['test'].num_examples

In [12]:
numtest=tf.cast(numtest,dtype=tf.int64)

In [117]:
next(iter(mtrain))

(<tf.Tensor: shape=(28, 28, 1), dtype=uint8, numpy=
 array([[[  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0]],
 
        [[  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0]],
 
        [[  0],
         [  0],
         [  0]

In [13]:
def scale(image,label):
    image=tf.cast(image,tf.float32)
    image /=255.
    return image,label    

In [14]:
scaletrainandvalidation=mtrain.map(scale)

In [15]:
scaletrainandvalidation

<_MapDataset element_spec=(TensorSpec(shape=(28, 28, 1), dtype=tf.float32, name=None), TensorSpec(shape=(), dtype=tf.int64, name=None))>

In [35]:
scaletest=mtest.map(scale)

In [17]:
bufersize=100

In [18]:
shufledatatrainandvalidation=scaletrainandvalidation.shuffle(bufersize)

In [19]:
traindata=shufledatatrainandvalidation.skip(numvalidation)
valdata=shufledatatrainandvalidation.take(numvalidation)

In [20]:
batchsize=50

In [21]:
traindata=traindata.batch(batchsize)

In [22]:
valdata=valdata.batch(numvalidation)

In [36]:
testdata=scaletest.batch(numtest)

In [30]:
valinput,valtarget=next(iter(valdata))

In [33]:
valdata

<_BatchDataset element_spec=(TensorSpec(shape=(None, 28, 28, 1), dtype=tf.float32, name=None), TensorSpec(shape=(None,), dtype=tf.int64, name=None))>

In [32]:
valtarget

<tf.Tensor: shape=(6000,), dtype=int64, numpy=array([9, 5, 6, ..., 7, 6, 7], dtype=int64)>

In [34]:
valinput

<tf.Tensor: shape=(6000, 28, 28, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
   

In [25]:
input=784
output=10
hidenlayersize=200
model=tf.keras.Sequential([
    
 tf.keras.layers.Flatten(input_shape=(28,28,1))   ,
 tf.keras.layers.Dense(hidenlayersize,activation='relu'),
 tf.keras.layers.Dense(hidenlayersize,activation='relu'),
 tf.keras.layers.Dense(hidenlayersize,activation='relu'),
 tf.keras.layers.Dense(output,activation='softmax')    
])

In [26]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [27]:
numepoch=10

In [28]:
model.fit(traindata,epochs=numepoch,validation_data=(valinput,valtarget),verbose=1)

Epoch 1/10
1080/1080 [==============================] - 8s 4ms/step - loss: 0.2309 - accuracy: 0.9298 - val_loss: 0.1362 - val_accuracy: 0.9580
Epoch 2/10
1080/1080 [==============================] - 4s 3ms/step - loss: 0.0928 - accuracy: 0.9723 - val_loss: 0.1132 - val_accuracy: 0.9658
Epoch 3/10
1080/1080 [==============================] - 4s 3ms/step - loss: 0.0606 - accuracy: 0.9816 - val_loss: 0.0995 - val_accuracy: 0.9698
Epoch 4/10
1080/1080 [==============================] - 4s 3ms/step - loss: 0.0473 - accuracy: 0.9854 - val_loss: 0.0997 - val_accuracy: 0.9720
Epoch 5/10
1080/1080 [==============================] - 4s 4ms/step - loss: 0.0404 - accuracy: 0.9869 - val_loss: 0.1252 - val_accuracy: 0.9670
Epoch 6/10
1080/1080 [==============================] - 4s 3ms/step - loss: 0.0319 - accuracy: 0.9892 - val_loss: 0.1150 - val_accuracy: 0.9693
Epoch 7/10
1080/1080 [==============================] - 4s 3ms/step - loss: 0.0259 - accuracy: 0.9911 - val_loss: 0.1243 - val_accuracy:

In [37]:
model.evaluate(testdata)

1/1 [==============================] - 0s 226ms/step - loss: 0.0988 - accuracy: 0.9792


[0.09878038614988327, 0.979200005531311]