In [95]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression as lr
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_selection import f_regression as ls
 

In [31]:
rawdata=pd.read_csv('Multiple linear regression.csv')

In [32]:
data=rawdata.copy()

In [33]:
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [34]:
y=data.iloc[:,2:3]
x=data.iloc[:,0:2]

In [35]:
y

GPA
0   2.40
1   2.52
2   2.54
3   2.74
4   2.83
..   ...
79  3.71
80  3.71
81  3.73
82  3.76
83  3.81

[84 rows x 1 columns]

In [36]:
x

SAT  Rand 1,2,3
0   1714           1
1   1664           3
2   1760           3
3   1685           3
4   1693           2
..   ...         ...
79  1936           3
80  1810           1
81  1987           3
82  1962           1
83  2050           2

[84 rows x 2 columns]

In [37]:
model=lr()

In [38]:
model.fit(x,y)

LinearRegression()

In [16]:
model.coef_

array([[ 0.00165354, -0.00826982]])

In [17]:
model.intercept_

array([0.29603261])

In [103]:
pdata=pd.DataFrame({'SAT':[1520,1252,1952,2201],'Rand 1,2,3':[1,2,2,3]})

In [104]:
pdata2=pd.DataFrame({'SAT':[1520,1252,1952,2201],'Rand 1,2,3':[1,2,2,3]})

In [40]:
pdata

SAT  Rand 1,2,3
0  1520           1
1  1252           2
2  1952           2
3  2201           3

In [41]:
model.predict(pdata)

array([[2.80114633],
       [2.3497273 ],
       [3.50720656],
       [3.91066865]])

In [42]:
pr2=model.predict(pdata)

In [24]:
pdata['predict']=model.predict(pdata)

In [43]:
pdata2=pdata.copy()

In [47]:
pr2

array([[2.80114633],
       [2.3497273 ],
       [3.50720656],
       [3.91066865]])

In [48]:
pr=pd.DataFrame(data=pr2)

In [76]:
pr

0
0  2.801146
1  2.349727
2  3.507207
3  3.910669

In [78]:
pdata2=pdata2.join(pr)

pdata2

SAR   SAT  Rand 1,2,3         0
0    1520           1  2.801146
1    1252           2  2.349727
2    1952           2  3.507207
3    2201           3  3.910669

In [92]:
pdata2.columns.rename('Rand 1,2,3','Predict')

In [93]:
pdata2

Rand 1,2,3   SAT  Rand 1,2,3         0
0           1520           1  2.801146
1           1252           2  2.349727
2           1952           2  3.507207
3           2201           3  3.910669

In [99]:
ls=ls(x,y)

c:\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [100]:
ls

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [101]:
pvalue=ls[1]
fscore=ls[0]

In [111]:
pvalue

array([7.19951844e-11, 6.76291372e-01])

In [102]:
pvalue.round(3)

array([0.   , 0.676])

In [105]:
sumaray=pd.DataFrame(data=pdata2.columns.values,columns=['fetuere'])

In [106]:
sumaray

fetuere
0         SAT
1  Rand 1,2,3

In [132]:
model.coef_

array([[ 0.00165354, -0.00826982]])

In [129]:
c=model.coef_
c=c[0][:]
c

array([ 0.00165354, -0.00826982])

In [130]:
sumaray['coef']=c
sumaray['pvalu']=pvalue.round(3)

In [131]:
sumaray

fetuere      coef  pvalu
0         SAT  0.001654  0.000
1  Rand 1,2,3 -0.008270  0.676