In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split as st
from sklearn.preprocessing import normalize as sn
import seaborn as sns
sns.set()

In [3]:
n= 1000

In [37]:
age=np.random.uniform(20,60,(n,1)).round(0)

In [38]:
height=np.random.uniform(150,200,(n,1)).round(0)

In [23]:
weight=np.random.uniform(50,130,(n,1)).round(0)


In [34]:
smoke=np.random.random_integers(0,1,(n,1))

C:\Users\Data Sciense\AppData\Local\Temp\ipykernel_13260\4095801921.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 1 + 1) instead
  smoke=np.random.random_integers(0,1,(n,1))


In [36]:
health=np.random.random_integers(0,1,(n,1))

C:\Users\Data Sciense\AppData\Local\Temp\ipykernel_13260\3235240103.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 1 + 1) instead
  health=np.random.random_integers(0,1,(n,1))


In [40]:
x=np.column_stack((age,height,weight,smoke))

In [41]:
x

array([[ 60., 167.,  68.,   1.],
       [ 40., 154., 130.,   0.],
       [ 39., 152.,  87.,   1.],
       ...,
       [ 36., 163., 101.,   0.],
       [ 52., 185.,  97.,   0.],
       [ 32., 156., 130.,   0.]])

In [43]:
xtrain,xtest,ytrean,ytest=st(x,health,test_size=0.2,random_state=143)

In [44]:
traindata=np.savez('traindata',input=xtrain,target=ytrean)

In [45]:
testdata=np.savez('testdata',input=xtest,target=ytest)

In [47]:
trdata=np.load('traindata.npz')

In [48]:
tedata=np.load('testdata.npz')

In [51]:
model=tf.keras.Sequential([tf.keras.layers.Dense(1)])
compile=model.compile(loss='mean_squared_error')
model.fit(trdata['input'],trdata['target'],verbose=1,epochs=500)

Epoch 1/500
25/25 [==============================] - 0s 842us/step - loss: 66933.0156
Epoch 2/500
25/25 [==============================] - 0s 959us/step - loss: 62706.6953
Epoch 3/500
25/25 [==============================] - 0s 880us/step - loss: 58939.4492
Epoch 4/500
25/25 [==============================] - 0s 876us/step - loss: 55291.5117
Epoch 5/500
25/25 [==============================] - 0s 823us/step - loss: 51769.6914
Epoch 6/500
25/25 [==============================] - 0s 793us/step - loss: 48360.9219
Epoch 7/500
25/25 [==============================] - 0s 880us/step - loss: 45074.7188
Epoch 8/500
25/25 [==============================] - 0s 827us/step - loss: 41914.8945
Epoch 9/500
25/25 [==============================] - 0s 830us/step - loss: 38856.0117
Epoch 10/500
25/25 [==============================] - 0s 955us/step - loss: 35910.9414
Epoch 11/500
25/25 [==============================] - 0s 855us/step - loss: 33096.0195
Epoch 12/500
25/25 [==============================] 

In [59]:
model.predict_on_batch(tedata['input']).round(5)

array([[0.61859],
       [0.59736],
       [0.6344 ],
       [0.64081],
       [0.61274],
       [0.54979],
       [0.58978],
       [0.58463],
       [0.64016],
       [0.62685],
       [0.62789],
       [0.60873],
       [0.57117],
       [0.64433],
       [0.59424],
       [0.62108],
       [0.55508],
       [0.58632],
       [0.59202],
       [0.6387 ],
       [0.63964],
       [0.62389],
       [0.56805],
       [0.60549],
       [0.58038],
       [0.61895],
       [0.59646],
       [0.62337],
       [0.64241],
       [0.6198 ],
       [0.56688],
       [0.62191],
       [0.61753],
       [0.56224],
       [0.61015],
       [0.54267],
       [0.60629],
       [0.57763],
       [0.56496],
       [0.6088 ],
       [0.60457],
       [0.59075],
       [0.61277],
       [0.61801],
       [0.62375],
       [0.5888 ],
       [0.56304],
       [0.63318],
       [0.56208],
       [0.5883 ],
       [0.6395 ],
       [0.60574],
       [0.61841],
       [0.57122],
       [0.58234],
       [0.

In [35]:
smoke

array([[1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
    

In [21]:
age

array([[44.],
       [41.],
       [45.],
       [49.],
       [42.],
       [29.],
       [48.],
       [56.],
       [30.],
       [36.],
       [20.],
       [27.],
       [24.],
       [44.],
       [29.],
       [23.],
       [33.],
       [50.],
       [51.],
       [44.],
       [38.],
       [35.],
       [25.],
       [53.],
       [22.],
       [41.],
       [41.],
       [59.],
       [26.],
       [34.],
       [20.],
       [31.],
       [56.],
       [20.],
       [50.],
       [58.],
       [54.],
       [53.],
       [25.],
       [58.],
       [28.],
       [31.],
       [53.],
       [38.],
       [51.],
       [27.],
       [32.],
       [28.],
       [35.],
       [25.],
       [34.],
       [26.],
       [29.],
       [54.],
       [36.],
       [39.],
       [47.],
       [35.],
       [42.],
       [21.],
       [50.],
       [37.],
       [20.],
       [34.],
       [34.],
       [36.],
       [47.],
       [52.],
       [44.],
       [21.],
       [31.],
      