In [2]:
import numpy as np
import pandas as pd
import tensorflow_datasets as tfds
import tensorflow as tf

In [3]:
mnistdata,mnistinfo=tfds.load('mnist',as_supervised=True,with_info=True)

In [4]:
countval=0.1*mnistinfo.splits['train'].num_examples

In [5]:
countval=tf.cast(countval,tf.int64)

In [6]:
countval

<tf.Tensor: shape=(), dtype=int64, numpy=6000>

In [7]:
counttest=mnistinfo.splits['test'].num_examples

In [8]:
counttest=tf.cast(counttest,tf.int64)

In [9]:
bufer=1000

In [10]:
mnistdatatrain=mnistdata['train']

In [11]:
mnistdatatest=mnistdata['test']

In [12]:
mnistdatatrain=mnistdatatrain.shuffle(bufer)

In [13]:
mnistdataval=mnistdatatrain.take(countval)
mnistdatabenchtrain=mnistdatatrain.skip(countval)

In [14]:
for i,j in mnistdatabenchtrain.take(48):
    print(i,'---------',j)

tf.Tensor(
[[[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  

In [15]:
def scale(image,label):
    image=tf.cast(image,tf.float64)
    image/=255.
    return image,label

In [16]:
mnistdataval=mnistdataval.map(scale)
mnistdatatest=mnistdatatest.map(scale)
mnistdatabenchtrain=mnistdatabenchtrain.map(scale)

In [17]:
batch=100

In [18]:
mnistdataval=mnistdataval.batch(countval)

In [19]:
mnistdatatest=mnistdatatest.batch(counttest)

In [20]:
mnistdatabenchtrain=mnistdatabenchtrain.batch(batch)

In [21]:
valdata,valtarget=next(iter(mnistdataval))

In [22]:
hidenlayer=50

In [23]:
model=tf.keras.Sequential([
tf.keras.layers.Flatten(input_shape=(28,28,1)) ,
tf.keras.layers.Dense(hidenlayer,activation='relu') ,  
tf.keras.layers.Dense(hidenlayer,activation='relu'),
tf.keras.layers.Dense(hidenlayer,activation='relu'),
tf.keras.layers.Dense(hidenlayer,activation='relu'),
tf.keras.layers.Dense(10,activation='softmax')   
])

In [24]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [25]:
model.fit(mnistdatabenchtrain,validation_data=(valdata,valtarget),epochs=6,verbose=2)

Epoch 1/6
540/540 - 3s - loss: 0.4121 - accuracy: 0.8756 - val_loss: 0.2052 - val_accuracy: 0.9397 - 3s/epoch - 6ms/step
Epoch 2/6
540/540 - 1s - loss: 0.1681 - accuracy: 0.9496 - val_loss: 0.1825 - val_accuracy: 0.9435 - 1s/epoch - 3ms/step
Epoch 3/6
540/540 - 1s - loss: 0.1308 - accuracy: 0.9601 - val_loss: 0.1626 - val_accuracy: 0.9525 - 1s/epoch - 2ms/step
Epoch 4/6
540/540 - 1s - loss: 0.1070 - accuracy: 0.9675 - val_loss: 0.1352 - val_accuracy: 0.9597 - 1s/epoch - 2ms/step
Epoch 5/6
540/540 - 1s - loss: 0.0889 - accuracy: 0.9732 - val_loss: 0.1484 - val_accuracy: 0.9557 - 1s/epoch - 2ms/step
Epoch 6/6
540/540 - 1s - loss: 0.0770 - accuracy: 0.9762 - val_loss: 0.1286 - val_accuracy: 0.9612 - 1s/epoch - 2ms/step


In [26]:
model.evaluate(mnistdatatest)

1/1 [==============================] - 0s 451ms/step - loss: 0.1086 - accuracy: 0.9682


[0.10857643932104111, 0.9682000279426575]