In [2]:
import numpy as np
import pandas as pd
import tensorflow_datasets as tfds
import tensorflow as tf

In [3]:
mnistdata,mnistinfo=tfds.load('mnist',as_supervised=True,with_info=True)

In [4]:
countval=0.1*mnistinfo.splits['train'].num_examples

In [5]:
countval=tf.cast(countval,tf.int64)

In [6]:
countval

<tf.Tensor: shape=(), dtype=int64, numpy=6000>

In [7]:
counttest=mnistinfo.splits['test'].num_examples

In [8]:
counttest=tf.cast(counttest,tf.int64)

In [9]:
bufer=1000

In [10]:
mnistdatatrain=mnistdata['train']

In [11]:
mnistdatatest=mnistdata['test']

In [12]:
mnistdatatrain=mnistdatatrain.shuffle(bufer)

In [13]:
mnistdataval=mnistdatatrain.take(countval)
mnistdatabenchtrain=mnistdatatrain.skip(countval)

In [14]:
for i,j in mnistdatabenchtrain.take(48):
    print(i,'---------',j)

tf.Tensor(
[[[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  

In [15]:
def scale(image,label):
    image=tf.cast(image,tf.float64)
    image/=255.
    return image,label

In [16]:
mnistdataval=mnistdataval.map(scale)
mnistdatatest=mnistdatatest.map(scale)
mnistdatabenchtrain=mnistdatabenchtrain.map(scale)

In [17]:
batch=100

In [18]:
mnistdataval=mnistdataval.batch(countval)

In [19]:
mnistdatatest=mnistdatatest.batch(counttest)

In [20]:
mnistdatabenchtrain=mnistdatabenchtrain.batch(batch)

In [21]:
valdata,valtarget=next(iter(mnistdataval))

In [22]:
hidenlayer=50

In [23]:
model=tf.keras.Sequential([
tf.keras.layers.Flatten(input_shape=(28,28,1)) ,
tf.keras.layers.Dense(hidenlayer,activation='relu') ,  
tf.keras.layers.Dense(hidenlayer,activation='relu'),
tf.keras.layers.Dense(hidenlayer,activation='relu'),
tf.keras.layers.Dense(hidenlayer,activation='relu'),
tf.keras.layers.Dense(10,activation='softmax')   
])

In [24]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [25]:
model.fit(mnistdatabenchtrain,validation_data=(valdata,valtarget),epochs=6,verbose=2)

Epoch 1/6
540/540 - 3s - loss: 0.4269 - accuracy: 0.8742 - val_loss: 0.2200 - val_accuracy: 0.9322 - 3s/epoch - 5ms/step
Epoch 2/6
540/540 - 1s - loss: 0.1772 - accuracy: 0.9471 - val_loss: 0.1532 - val_accuracy: 0.9525 - 1s/epoch - 2ms/step
Epoch 3/6
540/540 - 1s - loss: 0.1321 - accuracy: 0.9596 - val_loss: 0.1262 - val_accuracy: 0.9605 - 1s/epoch - 2ms/step
Epoch 4/6
540/540 - 1s - loss: 0.1057 - accuracy: 0.9671 - val_loss: 0.1161 - val_accuracy: 0.9640 - 1s/epoch - 2ms/step
Epoch 5/6
540/540 - 1s - loss: 0.0867 - accuracy: 0.9727 - val_loss: 0.1146 - val_accuracy: 0.9668 - 1s/epoch - 2ms/step
Epoch 6/6
540/540 - 1s - loss: 0.0739 - accuracy: 0.9774 - val_loss: 0.1165 - val_accuracy: 0.9648 - 1s/epoch - 2ms/step


In [26]:
model.evaluate(mnistdatatest)

1/1 [==============================] - 1s 532ms/step - loss: 0.1111 - accuracy: 0.9675


[0.11108862608671188, 0.9674999713897705]