In [1]:
import numpy as np
from sklearn.model_selection import train_test_split as tts

In [22]:
a=np.arange(1,200)
b=np.arange(1000,1199)

In [26]:
traintesta=tts(a)
traintestb=tts(b)
tr1,tr2,tr3,tr4=tts(a,b,random_state=20)


In [11]:
aa,ab=traintesta
ba,bb=traintestb

In [12]:
aa

array([ 27, 106, 151, 196, 104,  30,  39, 144, 199, 175, 187,  33, 102,
        55,  51, 186, 195, 160, 127, 135, 157, 189, 107, 105,  20, 110,
       190,  35, 158,  44, 100, 183,  47,  64,  91,  40, 179, 174,  96,
        42,  36, 103,  32,  72,  89,  80, 146, 197,  94,  57,  38,   9,
       141, 153,  56, 101,  16, 132, 126,  63, 142, 182, 134,  73, 125,
        18,  81, 168,  53,  82,  52, 150, 194, 171,  12,  85,  86,  93,
       170, 133,  21,  68,  49, 180, 162, 128,   2, 163, 161,  71,  87,
       159, 129,  10, 124,  13, 120, 169, 143,   3,  43,  22,  98, 176,
       167,  90,  61, 123,  41, 117,  70,  78,  84,  77,  76,  19,  11,
       188,  75, 181, 177,  23, 108,  74,  46,  97,  25,  88, 166,  62,
       136, 173,  34,  31,  66, 148,  17,  28,  24, 198,   1, 140,  54,
        79,   8,   6, 164, 116, 115])

In [21]:
tr1,tr2=tts(a,b,random_state=20)

ValueError: Found input variables with inconsistent numbers of samples: [199, 200]

In [27]:
tr1,tr2,tr3,tr4

(array([ 13, 130,  52, 153,  89,   2,  56,  81, 161,  65, 135,  63,  21,
         22,  46, 129,  93, 162,  30,  91,  36, 108,  92, 105, 165,  69,
         38,  99,   1, 156,  12, 136,  50,  31,  66, 198,  67, 104,  42,
        179, 118,  58,   3,  70,  75,  51, 109, 164,  59, 101,  57,  32,
         15, 121,  88,  40, 107, 103, 168,  74,  82,  55, 125, 140,  77,
         97,  53,  24, 120, 133,  10,  39, 173,  54,  96, 126,  49, 117,
         20,  37, 128, 124,  61, 154, 141, 189,  18, 115, 116, 159,  83,
        181, 160,   9, 191,  28,   5, 143, 193,  71, 197, 169,  95,  43,
         34,  94, 147,  25,  79, 172, 158, 190, 171,  80, 170, 186,  44,
        146,   4,  19, 194, 182,  11,  33, 111,  84,  62, 132,  26, 142,
        188,   7,   8, 102, 106, 145,  17,  27,  41, 119, 163,  72,  23,
         76, 149, 138, 157,  16, 100]),
 array([150,  29,  14, 178, 110, 166, 177, 196,  48, 180, 137,  78, 187,
        144,  85, 175, 155, 167, 122, 192, 176, 114,  90, 151, 185, 148,
        199

In [38]:
tr1.shape,tr2.shape,tr3.shape,tr4.shape




((149,), (50,), (149,), (50,))

In [47]:
tr1.reshape(-1,1)

array([[ 13],
       [130],
       [ 52],
       [153],
       [ 89],
       [  2],
       [ 56],
       [ 81],
       [161],
       [ 65],
       [135],
       [ 63],
       [ 21],
       [ 22],
       [ 46],
       [129],
       [ 93],
       [162],
       [ 30],
       [ 91],
       [ 36],
       [108],
       [ 92],
       [105],
       [165],
       [ 69],
       [ 38],
       [ 99],
       [  1],
       [156],
       [ 12],
       [136],
       [ 50],
       [ 31],
       [ 66],
       [198],
       [ 67],
       [104],
       [ 42],
       [179],
       [118],
       [ 58],
       [  3],
       [ 70],
       [ 75],
       [ 51],
       [109],
       [164],
       [ 59],
       [101],
       [ 57],
       [ 32],
       [ 15],
       [121],
       [ 88],
       [ 40],
       [107],
       [103],
       [168],
       [ 74],
       [ 82],
       [ 55],
       [125],
       [140],
       [ 77],
       [ 97],
       [ 53],
       [ 24],
       [120],
       [133],
       [ 10],
      