In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf
import tensorflow_datasets as tfds
import ipywidgets as iw

In [277]:
#%pip install --user --upgrade ipywidgets 

In [3]:
mnist,mnistinfo=tfds.load(name='mnist',with_info=True,as_supervised=True)

In [4]:
mnistinfo

tfds.core.DatasetInfo(
    name='mnist',
    full_name='mnist/3.0.1',
    description="""
    The MNIST database of handwritten digits.
    """,
    homepage='http://yann.lecun.com/exdb/mnist/',
    data_path='C:\\Users\\Data Sciense\\tensorflow_datasets\\mnist\\3.0.1',
    file_format=tfrecord,
    download_size=11.06 MiB,
    dataset_size=21.00 MiB,
    features=FeaturesDict({
        'image': Image(shape=(28, 28, 1), dtype=uint8),
        'label': ClassLabel(shape=(), dtype=int64, num_classes=10),
    }),
    supervised_keys=('image', 'label'),
    disable_shuffling=False,
    splits={
        'test': <SplitInfo num_examples=10000, num_shards=1>,
        'train': <SplitInfo num_examples=60000, num_shards=1>,
    },
    citation="""@article{lecun2010mnist,
      title={MNIST handwritten digit database},
      author={LeCun, Yann and Cortes, Corinna and Burges, CJ},
      journal={ATT Labs [Online]. Available: http://yann.lecun.com/exdb/mnist},
      volume={2},
      year={2010}
    

In [5]:
countvaldition=mnistinfo.splits['train'].num_examples

In [6]:
numtest=mnistinfo.splits['test'].num_examples

In [7]:
countvaldition=0.1*countvaldition

In [8]:
countvaldition=tf.cast(countvaldition,dtype=tf.int64)

In [9]:
countvaldition

<tf.Tensor: shape=(), dtype=int64, numpy=6000>

In [10]:
mnisttrainval=mnist['train']

In [11]:
mnisttest=mnist['test']

In [12]:
mnisttrainval.take(5)

<_TakeDataset element_spec=(TensorSpec(shape=(28, 28, 1), dtype=tf.uint8, name=None), TensorSpec(shape=(), dtype=tf.int64, name=None))>

In [13]:
mnisttrainval=mnisttrainval.shuffle(100)

In [14]:
mylist=[]
for i in mnisttrainval.take(2):
   mylist.append(i) 
mylistframe=pd.DataFrame(mylist)
print(mylistframe)


                                                   0  \
0  (((tf.Tensor(0, shape=(), dtype=uint8)), (tf.T...   
1  (((tf.Tensor(0, shape=(), dtype=uint8)), (tf.T...   

                                     1  
0  tf.Tensor(9, shape=(), dtype=int64)  
1  tf.Tensor(4, shape=(), dtype=int64)  


In [15]:
next(iter(mnisttrainval.take(5)))

(<tf.Tensor: shape=(28, 28, 1), dtype=uint8, numpy=
 array([[[  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0]],
 
        [[  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0],
         [  0]],
 
        [[  0],
         [  0],
         [  0]

In [16]:
mnistval=mnisttrainval.take(countvaldition)
mnisttrain=mnisttrainval.skip(countvaldition)

In [17]:
def scale (image,label):
    image=tf.cast(image,tf.float32)
    image/=255.
    return image,label

In [18]:
mnisttrainval=mnisttrainval.map(scale)

In [19]:
mnistval.map(scale)
mnisttrain.map(scale)
mnisttest.map(scale)

<_MapDataset element_spec=(TensorSpec(shape=(28, 28, 1), dtype=tf.float32, name=None), TensorSpec(shape=(), dtype=tf.int64, name=None))>

In [20]:
bufersize=100

In [21]:
mnisttrainval=mnisttrainval.shuffle(bufersize)

In [22]:
valt,tart=next(iter(mnistval))

In [23]:
input=784
output=10
hidenlayersize=200
model=tf.keras.Sequential([
    
 tf.keras.layers.Flatten(input_shape=(28,28,1))   ,
 tf.keras.layers.Dense(hidenlayersize,activation='relu'),
 tf.keras.layers.Dense(hidenlayersize,activation='relu'),
 tf.keras.layers.Dense(hidenlayersize,activation='relu'),
 tf.keras.layers.Dense(output,activation='softmax')    
])

In [24]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [25]:
batchsize=50

In [26]:
mnisttrain=mnisttrain.batch(batchsize)

In [27]:
mnistval=mnistval.batch(countvaldition)

In [28]:
mnisttest=mnisttest.batch(numtest)

In [29]:
numepoch=5

In [30]:
mnistval

<_BatchDataset element_spec=(TensorSpec(shape=(None, 28, 28, 1), dtype=tf.uint8, name=None), TensorSpec(shape=(None,), dtype=tf.int64, name=None))>

In [31]:
tart

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [32]:
valt

<tf.Tensor: shape=(28, 28, 1), dtype=uint8, numpy=
array([[[  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0]],

       [[  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0]],

       [[  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],


In [33]:
model.fit(mnisttrain,validation_data=(valt,tart),epochs=numepoch,verbose=1)

Epoch 1/5
1065/1080 [============================>.] - ETA: 0s - loss: 1.1042 - accuracy: 0.8808

IndexError: tuple index out of range

In [ ]:
model.evaluate(mnisttest)

1/1 [==============================] - 0s 261ms/step - loss: 0.1293 - accuracy: 0.9668


[0.12926088273525238, 0.9667999744415283]

In [ ]:
mnisttrain

<_BatchDataset element_spec=(TensorSpec(shape=(None, 28, 28, 1), dtype=tf.uint8, name=None), TensorSpec(shape=(None,), dtype=tf.int64, name=None))>

In [ ]:
model.evaluate(mnisttest)

NameError: name 'model' is not defined